template: |
  ## Changes

  $CHANGES
  
autolabeler:
  - label: 'documentation'
    files:
      - '*.mdx'
  - label: 'docs'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🧰 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'patch'
  - title: '📖 Documentation'
    label: 'docs'
    

